import type { NextPage } from "next";
import Head from "next/head";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub } from "@fortawesome/free-brands-svg-icons";

config.autoAddCss = false;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>emileyr</title>
        <meta name="description" content="Generated by create-t3-app <3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4 text-center">
        <section>
          <h1 className=" text-5xl font-bold text-emerald-400"><span className="font-mono">o/</span> Hello,</h1>
          <p>welcome to my portfolio!</p>
        </section>
        <section className="p-5">
          <p className="animate-fade-in-1">...</p>
          <p className="animate-fade-in-2">uhh, its a work in progress</p>
          <p className="animate-fade-in-3">
            <a href="https://github.com/emileyr" className="hover:text-emerald-400">
              <FontAwesomeIcon icon={faGithub} /> emileyr
            </a>
          </p>
        </section>
      </main>
    </>
  );
};

export default Home;
